### ISSUE TITLE
Add CMS examples in /examples directory

### ISSUE THREAD

**Issue by domitriusclark** [domitriusclark/mdnext#10]
I'm going to be working on building out different examples of this repo with current popular CMS providers.

I'll be banging out a GraphCMS example first, but would love to see what else we can get in there.

**Comment by grikomsn** [comment]
If located in `/examples`, would it mean cloning the template with all the examples? What about separate repo containing examples?

**Comment by domitriusclark** [comment]
Thinking of maybe going the monorepo route after some discussion in the Party Corgi chat. Have any thoughts there?

**Comment by grikomsn** [comment]
Since the examples doesn't interact with the main template, I think an `/examples` directory would be great! If users apply the template via `degit`, we can use [`degit` actions](https://github.com/Rich-Harris/degit#remove) to remove specific files/directories.

For example, this action will remove the `/examples` directory when `npx degit domitriusclark/mdnext my-new-blog`:

```json
// degit.json
[
	{
		"action": "remove",
		"files": ["examples"]
	}
]
```

With the caveat is needing to `git init` and push locally first, rather that creating via GitHub repo templates.
