### ISSUE TITLE
Upgrade Chakra to v1 🕺

### ISSUE THREAD

**Issue by molebox** [domitriusclark/mdnext#68]
Hey Dom! 

Chakra v1 has officially been released and they have changed the packages again. Would be cool to get those updates in. I can do it if you want?

Peace

**Comment by bleafman** [comment]
Hey Dom,

Just as an FYI -- the `mdnext-blog` errors when you try to `yarn dev` with `Cannot find module 'framer-motion'`.

I'm assuming it's because in the `package.json` it has ` "@chakra-ui/core": "^1.0.0-rc.3"`, which installs `1.0.0-rc.8` and it looks like `rc.8` has a bunch of dependencies that use `framer-motion`.

Happy to put in a PR to bump the blog template.

P.S. Loving `mdnext`! I was just working to stand a personal blog this weekend with `next` and `mdx` but got side tracked trying to figure out a good way to cleanly abstract `next-mdx-remote`. Thanks for figuring that out =)

**Comment by domitriusclark** [comment]
Finally got some time to focus in on `mdnext` this weekend :) 

Getting around to bringing all the templates up to speed with upgrades across the board, including and especially the blog

Thanks ya'll
